# Generated by Django 4.2.5 on 2023-11-03 12:22

import common.models
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Invitation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            (
                                common.models.InvitationStatus["PENDING"],
                                common.models.InvitationStatus["PENDING"],
                            ),
                            (
                                common.models.InvitationStatus["APPROVED"],
                                common.models.InvitationStatus["APPROVED"],
                            ),
                            (
                                common.models.InvitationStatus["REJECTED"],
                                common.models.InvitationStatus["REJECTED"],
                            ),
                            (
                                common.models.InvitationStatus["REVOKED"],
                                common.models.InvitationStatus["REVOKED"],
                            ),
                        ],
                        default=common.models.InvitationStatus["PENDING"],
                        max_length=30,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="UserRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            (
                                common.models.RequestStatus["PENDING"],
                                common.models.RequestStatus["PENDING"],
                            ),
                            (
                                common.models.RequestStatus["APPROVED"],
                                common.models.RequestStatus["APPROVED"],
                            ),
                            (
                                common.models.RequestStatus["REJECTED"],
                                common.models.RequestStatus["REJECTED"],
                            ),
                            (
                                common.models.RequestStatus["CANCELED"],
                                common.models.RequestStatus["CANCELED"],
                            ),
                        ],
                        default=common.models.RequestStatus["PENDING"],
                        max_length=30,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
