# Generated by Django 4.2.5 on 2023-11-01 14:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0003_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="request",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("APPROVED", "Approved"),
                    ("REJECTED", "Rejected"),
                    ("CANCELED", "Canceled"),
                    ("REVOKED", "Revoked"),
                ],
                default="Pending",
                max_length=30,
            ),
        ),
    ]
