# Generated by Django 4.2.5 on 2023-11-01 14:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0004_alter_request_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invitation",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("APPROVED", "Approved"),
                    ("REJECTED", "Rejected"),
                    ("REVOKED", "Revoked"),
                    ("CANCELED", "Canceled"),
                ],
                default="Pending",
                max_length=30,
            ),
        ),
    ]
