# Generated by Django 4.2.5 on 2023-11-04 17:52

import common.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone

import company.models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("is_visible", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name_plural": "Companies",
            },
        ),
        migrations.CreateModel(
            name="Invitation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            (
                                company.models.InvitationStatus["PENDING"],
                                company.models.InvitationStatus["PENDING"],
                            ),
                            (
                                company.models.InvitationStatus["APPROVED"],
                                company.models.InvitationStatus["APPROVED"],
                            ),
                            (
                                company.models.InvitationStatus["REJECTED"],
                                company.models.InvitationStatus["REJECTED"],
                            ),
                            (
                                company.models.InvitationStatus["REVOKED"],
                                company.models.InvitationStatus["REVOKED"],
                            ),
                        ],
                        default=company.models.InvitationStatus["PENDING"],
                        max_length=30,
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="company.company",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
