# Generated by Django 4.2.5 on 2023-11-01 13:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("common", "0003_initial"),
        ("company", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="members",
            field=models.ManyToManyField(
                blank=True, related_name="member_of", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="company",
            name="owner",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="owned_company",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="company",
            name="requests",
            field=models.ManyToManyField(
                blank=True, related_name="company_requests", to="common.request"
            ),
        ),
    ]
